Add support for an overlaid filesystem.

diff --git a/conf/init b/conf/init
--- a/conf/init
+++ b/conf/init
@@ -157,6 +157,7 @@ for i in ${CMDLINE}
   fi 
 done
 mkdir -p /mnt/live_root             #root fs
+mkdir -p /mnt/live_overlay          #overlay fs
 mkdir -p /mnt/live_cdrom
 mkdir -p /mnt/tmpfs
 mkdir -p /mnt/unionfs
@@ -219,8 +220,9 @@ do
 	if [ -e /mnt/live_cdrom/root.squashfs ]
 	then
 	  echo accessing live_cd image at $__nodes
-	  mount /mnt/live_cdrom/root.squashfs /mnt/live_root -o loop,ro || (echo "failed, continueing"; continue; )
-	  mount -t aufs -o "br:/mnt/tmpfs:/mnt/live_root" none /mnt/unionfs || (echo "failed, continueing"; continue; )
+	  mount /mnt/live_cdrom/root.squashfs /mnt/live_root -o loop,ro || (echo "failed, continuing"; continue; )
+	  mount /mnt/live_cdrom/overlay.squashfs /mnt/live_overlay -o loop,ro || (echo "failed, continuing"; continue; )
+	  mount -t aufs -o "br:/mnt/tmpfs:/mnt/live_overlay:/mnt/live_root" none /mnt/unionfs || (echo "failed, continuing"; continue; )
 	  for mod in /mnt/live_cdrom/squashmod/*
 	    do
 	      if [ -f $mod ]
